permalink: /:categories/:year/:month/:day/:title:output_ext

collections:
  portfolio:
    output: true

defaults:
  - scope:
      path: ""
      type: "portfolio"
    values:
      layout: "project"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
